# Generated by Django 2.2.3 on 2020-03-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_like',
            name='count',
        ),
    ]
