# Generated by Django 2.2.3 on 2020-03-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_like',
            name='post',
            field=models.IntegerField(default=0),
        ),
    ]
