# Generated by Django 2.2.3 on 2020-03-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200307_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_like',
            name='post',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post_like',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
