# Generated by Django 2.2.3 on 2020-03-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200307_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_like',
            name='post',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post_like',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
