# Generated by Django 2.2.3 on 2020-03-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200308_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.IntegerField(default=0)),
                ('user', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Post_Comment',
                'verbose_name_plural': 'Post_Comments',
            },
        ),
    ]
