# Generated by Django 2.2.3 on 2020-03-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('likes',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
